language: cpp

sudo: false

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

script:
  - make spark_install
  - python tools/generate_mock_csv.py
  - python metrics/retention_events_signed.py
