language: cpp

sudo: false

python:
  - "2.7"


before_install:
  - echo "Before Install"

script:
  - make spark_install
  - python tools/generate_mock_csv.py
  - python metrics/retention_events_signed.py
